# ER-ServiceDesk/app/routes/auth.py
# Authentication routes.
#
# Provides login endpoint for user authentication.
# Uses the authentication service to validate credentials and issue tokens.
# This module fits into the API routing layer and exposes the public-facing
# authentication interface for clients of the ER‑ServiceDesk backend.

# ---------------------------------------------------------------------------
# Route Handlers
# ---------------------------------------------------------------------------

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.db.session import get_db
from app.services.auth_service import auth_service
from app.schemas.user import UserLogin

router = APIRouter(prefix="/auth", tags=["auth"])


@router.post("/login")
def login(credentials: UserLogin, db: Session = Depends(get_db)):
    """
    Authenticate the user using email and password and return an access token.

    Behavioral notes:
    - Delegates authentication logic to auth_service.authenticate.
    - Returns a token payload generated by auth_service.login.
    - Raises HTTPException(400) if credentials are invalid.
    """
    user = auth_service.authenticate(db, credentials.email, credentials.password)
    if not user:
        raise HTTPException(status_code=400, detail="Invalid credentials")

    return auth_service.login(user)
