# ER-ServiceDesk/app/core/config.py
"""
Strongly-typed application configuration, loaded from environment
variables (and .env locally) via Pydantic Settings.
"""

from pydantic_settings import BaseSettings

class Settings(BaseSettings):
    """Application configuration settings."""
    PROJECT_NAME: str = "ER Service Desk"
    DATABASE_URL: str
    REDIS_URL: str = "redis://redis:6379/0"
    SECRET_KEY: str
    ALGORITHM: str = "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 15

    # Separate, dedicated key for encrypting device user-account
    # passwords at rest (see app/core/encryption.py) -- deliberately
    # NOT SECRET_KEY, since reusing one key across different
    # cryptographic purposes (JWT signing vs. symmetric encryption) is
    # bad practice. Auto-generated by the installer the same way
    # SECRET_KEY is (GenerateRandomString(48) written to .env).
    DEVICE_ACCOUNT_ENCRYPTION_KEY: str = ""

    model_config = {"env_file": ".env", "env_file_encoding": "utf-8", "extra": "ignore"}

settings = Settings()