# ER-ServiceDesk/app/core/encryption.py
# Reversible encryption for data that must be decryptable later (unlike login passwords, which are one-way hashed).
"""
Reversible symmetric encryption for data that genuinely needs to come
back out as plaintext later -- unlike login passwords (see security.py,
one-way hashed, never decrypted), a device user account's password
needs to be shown to a tech looking at the customer's profile, since
it's often a Microsoft account password (the same credential unlocking
email/OneDrive/etc.), not just a local Windows login.

Uses Fernet (AES-128-CBC + HMAC, from the `cryptography` library) with
a key derived from settings.DEVICE_ACCOUNT_ENCRYPTION_KEY via PBKDF2 --
that setting is an arbitrary random string (auto-generated by the
installer the same way SECRET_KEY is), not itself a valid Fernet key,
so PBKDF2 turns it into one deterministically without needing any
installer-side change to generate base64-specific bytes.
"""

import base64
import hashlib

from cryptography.fernet import Fernet

from app.core.config import settings

# Fixed salt is acceptable here -- this isn't password hashing (where
# a unique salt per record defeats rainbow tables); it's a single
# application-wide key derivation, and the real secret is
# DEVICE_ACCOUNT_ENCRYPTION_KEY itself, not this salt.
_PBKDF2_SALT = b"er-servicedesk-device-account-encryption"
_PBKDF2_ITERATIONS = 480_000


def _get_fernet() -> Fernet:
    """
    Returns:
        A Fernet instance keyed from settings.DEVICE_ACCOUNT_ENCRYPTION_KEY.

    Raises:
        ValueError: If DEVICE_ACCOUNT_ENCRYPTION_KEY isn't set -- this
            is a hard failure, not a silent fallback, since silently
            using a weak/empty key would be a real security bug, not
            a convenience.
    """
    if not settings.DEVICE_ACCOUNT_ENCRYPTION_KEY:
        raise ValueError(
            "DEVICE_ACCOUNT_ENCRYPTION_KEY is not set -- required for "
            "device user account password encryption. Check .env."
        )

    derived = hashlib.pbkdf2_hmac(
        "sha256",
        settings.DEVICE_ACCOUNT_ENCRYPTION_KEY.encode("utf-8"),
        _PBKDF2_SALT,
        _PBKDF2_ITERATIONS,
        dklen=32,
    )
    fernet_key = base64.urlsafe_b64encode(derived)
    return Fernet(fernet_key)


def encrypt_password(plaintext: str) -> str:
    """
    Args:
        plaintext: The password to encrypt.

    Returns:
        The encrypted value, safe to store in the database as a string.
    """
    return _get_fernet().encrypt(plaintext.encode("utf-8")).decode("utf-8")


def decrypt_password(ciphertext: str) -> str:
    """
    Args:
        ciphertext: A value previously returned by encrypt_password().

    Returns:
        The original plaintext password.

    Raises:
        InvalidToken: If ciphertext is malformed or was encrypted with
            a different key (e.g. DEVICE_ACCOUNT_ENCRYPTION_KEY changed).
    """
    return _get_fernet().decrypt(ciphertext.encode("utf-8")).decode("utf-8")
